[project]
name = "csghub-mcp-server"
version = "0.1.0"
description = "CSGHub MCP Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.15.0",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = [
    "space",
    "model"
]